project_id = "rwzyvgralronyuzqwyhu"

[functions.api-playground]
verify_jwt = false

[functions.wert-widget]
verify_jwt = false

[functions.wert-webhook]
verify_jwt = false

[functions.generate-deposit-address]
verify_jwt = false